namespace SGX.SistemaChamado.Api.Authorization;

public static class PermissionPolicies
{
    public const string Prefixo = "Permissao:";

    public const string DashboardVisualizar = Prefixo + PermissoesConstants.DashboardVisualizar;
    public const string CadastrosVisualizar = Prefixo + PermissoesConstants.CadastrosVisualizar;
    public const string CadastrosGerenciar = Prefixo + PermissoesConstants.CadastrosGerenciar;
    public const string UsuariosGerenciar = Prefixo + PermissoesConstants.UsuariosGerenciar;
    public const string UsuariosAlterarPerfis = Prefixo + PermissoesConstants.UsuariosAlterarPerfis;
    public const string PerfisGerenciar = Prefixo + PermissoesConstants.PerfisGerenciar;
    public const string PerfisAlterarPermissoes = Prefixo + PermissoesConstants.PerfisAlterarPermissoes;
    public const string ParametrosGerenciar = Prefixo + PermissoesConstants.ParametrosGerenciar;
    public const string IntegracoesEmailVisualizar = Prefixo + PermissoesConstants.IntegracoesEmailVisualizar;
    public const string IntegracoesMicrosoftVisualizar = Prefixo + PermissoesConstants.IntegracoesMicrosoftVisualizar;
    public const string IntegracoesMicrosoftGerenciar = Prefixo + PermissoesConstants.IntegracoesMicrosoftGerenciar;
    public const string IntegracoesActiveDirectoryVisualizar = Prefixo + PermissoesConstants.IntegracoesActiveDirectoryVisualizar;
    public const string IntegracoesActiveDirectoryGerenciar = Prefixo + PermissoesConstants.IntegracoesActiveDirectoryGerenciar;
    public const string AutenticacaoProvedoresVisualizar = Prefixo + PermissoesConstants.AutenticacaoProvedoresVisualizar;
    public const string AutenticacaoProvedoresGerenciar = Prefixo + PermissoesConstants.AutenticacaoProvedoresGerenciar;
    public const string UsuariosRedefinirSenha = Prefixo + PermissoesConstants.UsuariosRedefinirSenha;
    public const string ChamadosAssumir = Prefixo + PermissoesConstants.ChamadosAssumir;
    public const string ChamadosAtribuir = Prefixo + PermissoesConstants.ChamadosAtribuir;
    public const string ChamadosEncerrar = Prefixo + PermissoesConstants.ChamadosEncerrar;
    public const string RoadmapVisualizar = Prefixo + PermissoesConstants.RoadmapVisualizar;
    public const string RoadmapGerenciar = Prefixo + PermissoesConstants.RoadmapGerenciar;
    public const string RoadmapImplementacoesVisualizar = Prefixo + PermissoesConstants.RoadmapImplementacoesVisualizar;
    public const string RoadmapImplementacoesGerenciar = Prefixo + PermissoesConstants.RoadmapImplementacoesGerenciar;
    public const string SlaVisualizar = Prefixo + PermissoesConstants.SlaVisualizar;
    public const string SlaCriar = Prefixo + PermissoesConstants.SlaCriar;
    public const string SlaEditar = Prefixo + PermissoesConstants.SlaEditar;
    public const string SlaExcluir = Prefixo + PermissoesConstants.SlaExcluir;
    public const string SlaAtivarDesativar = Prefixo + PermissoesConstants.SlaAtivarDesativar;
    public const string AuditoriaVisualizar = Prefixo + PermissoesConstants.AuditoriaVisualizar;
    public const string AuditoriaAutenticacaoVisualizar = Prefixo + PermissoesConstants.AuditoriaAutenticacaoVisualizar;
    public const string AuditoriaGerenciar = Prefixo + PermissoesConstants.AuditoriaGerenciar;
    public const string BaseConhecimentoVisualizar = Prefixo + PermissoesConstants.BaseConhecimentoVisualizar;
    public const string BaseConhecimentoGerenciar = Prefixo + PermissoesConstants.BaseConhecimentoGerenciar;
    public const string BaseConhecimentoPublicar = Prefixo + PermissoesConstants.BaseConhecimentoPublicar;
    public const string BaseConhecimentoArquivar = Prefixo + PermissoesConstants.BaseConhecimentoArquivar;
    public const string BaseConhecimentoVincularChamado = Prefixo + PermissoesConstants.BaseConhecimentoVincularChamado;
    public const string CatalogoServicosVisualizar = Prefixo + PermissoesConstants.CatalogoServicosVisualizar;
    public const string CatalogoServicosGerenciar = Prefixo + PermissoesConstants.CatalogoServicosGerenciar;
    public const string CatalogoServicosPublicar = Prefixo + PermissoesConstants.CatalogoServicosPublicar;
    public const string CatalogoServicosArquivar = Prefixo + PermissoesConstants.CatalogoServicosArquivar;
    public const string InventarioAtivosVisualizar = Prefixo + PermissoesConstants.InventarioAtivosVisualizar;
    public const string InventarioAtivosGerenciar = Prefixo + PermissoesConstants.InventarioAtivosGerenciar;
    public const string InventarioAtivosInativar = Prefixo + PermissoesConstants.InventarioAtivosInativar;
    public const string InventarioAtivosMovimentar = Prefixo + PermissoesConstants.InventarioAtivosMovimentar;
    public const string InventarioAtivosVincularChamado = Prefixo + PermissoesConstants.InventarioAtivosVincularChamado;
    public const string AprovacaoChamadosVisualizar = Prefixo + PermissoesConstants.AprovacaoChamadosVisualizar;
    public const string AprovacaoChamadosGerenciar = Prefixo + PermissoesConstants.AprovacaoChamadosGerenciar;
    public const string AprovacaoChamadosAprovar = Prefixo + PermissoesConstants.AprovacaoChamadosAprovar;
    public const string AprovacaoChamadosReprovar = Prefixo + PermissoesConstants.AprovacaoChamadosReprovar;
    public const string AprovacaoChamadosCancelar = Prefixo + PermissoesConstants.AprovacaoChamadosCancelar;
    public const string RelatoriosAvancadosVisualizar = Prefixo + PermissoesConstants.RelatoriosAvancadosVisualizar;
    public const string RelatoriosAvancadosExportar = Prefixo + PermissoesConstants.RelatoriosAvancadosExportar;
    public const string RelatoriosAvancadosGerencial = Prefixo + PermissoesConstants.RelatoriosAvancadosGerencial;
    public const string RelatoriosAvancadosOperacional = Prefixo + PermissoesConstants.RelatoriosAvancadosOperacional;
    public const string RelatoriosAvancadosAuditoria = Prefixo + PermissoesConstants.RelatoriosAvancadosAuditoria;
}
