// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SGX.SistemaChamado.Infrastructure.Persistence;

#nullable disable

namespace SGX.SistemaChamado.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SGXSistemaChamadoDbContext))]
    [Migration("20260703111542_SincronizarChecklistSprint8ExibicaoRespostasFormularioPortalSolicitante")]
    partial class SincronizarChecklistSprint8ExibicaoRespostasFormularioPortalSolicitante
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.AnexoChamado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("caminho");

                    b.Property<Guid>("ChamadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("chamado_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("nome_arquivo");

                    b.Property<string>("NomeArquivoArmazenado")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("nome_arquivo_armazenado");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanho_bytes");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoId");

                    b.ToTable("anexos_chamado");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.AprovacaoChamado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<Guid>("ChamadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("chamado_id");

                    b.Property<DateTime?>("ConcluidaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("concluida_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<string>("Justificativa")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("justificativa");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("SolicitadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("solicitada_em");

                    b.Property<Guid>("SolicitanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("solicitante_id");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoId")
                        .IsUnique();

                    b.HasIndex("SolicitanteId");

                    b.ToTable("aprovacoes_chamado");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.ArtigoBaseConhecimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("conteudo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<string>("PalavrasChave")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("palavras_chave");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("artigos_base_conhecimento");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.AtivoInventario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<Guid?>("DepartamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("departamento_id");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("identificador");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("localizacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nome");

                    b.Property<Guid?>("ResponsavelId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsavel_id");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("serial_number");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TipoAtivoInventarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("tipo_ativo_inventario_id");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("Identificador")
                        .IsUnique();

                    b.HasIndex("ResponsavelId");

                    b.HasIndex("TipoAtivoInventarioId");

                    b.ToTable("ativos_inventario");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.CalendarioCorporativo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<bool>("EhPadrao")
                        .HasColumnType("boolean")
                        .HasColumnName("eh_padrao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("calendarios_corporativos");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.CampoFormularioServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<Guid>("FormularioServicoVersaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("formulario_servico_versao_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("boolean")
                        .HasColumnName("obrigatorio");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<string>("Rotulo")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("rotulo");

                    b.Property<string>("TextoAjuda")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("texto_ajuda");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<bool>("Visivel")
                        .HasColumnType("boolean")
                        .HasColumnName("visivel");

                    b.HasKey("Id");

                    b.HasIndex("FormularioServicoVersaoId", "Nome")
                        .IsUnique()
                        .HasDatabaseName("ux_campo_form_serv_nome");

                    b.HasIndex("FormularioServicoVersaoId", "Ordem")
                        .IsUnique()
                        .HasDatabaseName("ux_campo_form_serv_ordem");

                    b.ToTable("campos_formulario_servico");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.CategoriaChamado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<Guid?>("DepartamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("departamento_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("categorias_chamado");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.Chamado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AprovacaoPendente")
                        .HasColumnType("boolean")
                        .HasColumnName("aprovacao_pendente");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<Guid?>("LocalUnidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("local_unidade_id");

                    b.Property<Guid?>("AprovacaoChamadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("aprovacao_chamado_id");

                    b.Property<Guid?>("AprovadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("aprovador_id");

                    b.Property<DateTime?>("AprovadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aprovado_em");

                    b.Property<DateTime>("AbertoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aberto_em");

                    b.Property<Guid?>("ArtigoBaseConhecimentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("artigo_base_conhecimento_id");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<Guid?>("CatalogoServicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalogo_servico_id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("descricao");

                    b.Property<Guid?>("DepartamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("departamento_id");

                    b.Property<DateTime?>("EncerradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("encerrado_em");

                    b.Property<Guid?>("FilaAtendimentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("fila_atendimento_id");

                    b.Property<Guid?>("GrupoTecnicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_tecnico_id");

                    b.Property<int?>("ImpactoChamado")
                        .HasColumnType("integer")
                        .HasColumnName("impacto_chamado");

                    b.Property<bool>("Interno")
                        .HasColumnType("boolean")
                        .HasColumnName("interno");

                    b.Property<bool>("OrigemEmail")
                        .HasColumnType("boolean")
                        .HasColumnName("origem_email");

                    b.Property<int?>("NaturezaChamado")
                        .HasColumnType("integer")
                        .HasColumnName("natureza_chamado");

                    b.Property<Guid>("PrioridadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("prioridade_id");

                    b.Property<Guid?>("ResponsavelId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsavel_id");

                    b.Property<bool>("RequerAprovacao")
                        .HasColumnType("boolean")
                        .HasColumnName("requer_aprovacao");

                    b.Property<Guid?>("SlaId")
                        .HasColumnType("uuid")
                        .HasColumnName("sla_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_id");

                    b.Property<Guid?>("SubcategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("subcategoria_id");

                    b.Property<Guid>("SolicitanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("solicitante_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.Property<Guid?>("TipoSolicitacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("tipo_solicitacao_id");

                    b.Property<int?>("UrgenciaChamado")
                        .HasColumnType("integer")
                        .HasColumnName("urgencia_chamado");

                    b.HasKey("Id");

                    b.HasIndex("AprovadorId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CatalogoServicoId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("FilaAtendimentoId");

                    b.HasIndex("GrupoTecnicoId");

                    b.HasIndex("LocalUnidadeId");

                    b.HasIndex("PrioridadeId");

                    b.HasIndex("ResponsavelId");

                    b.HasIndex("SlaId");

                    b.HasIndex("SolicitanteId");

                    b.HasIndex("StatusId");

                    b.HasIndex("SubcategoriaId");

                    b.HasIndex("TipoSolicitacaoId");

                    b.ToTable("chamados");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.CorrelacaoEmailChamado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<Guid>("ChamadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("chamado_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoId");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("correlacoes_email_chamado");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.PoliticaSla", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<Guid?>("CalendarioCorporativoId")
                        .HasColumnType("uuid")
                        .HasColumnName("calendario_corporativo_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<bool>("EhPadrao")
                        .HasColumnType("boolean")
                        .HasColumnName("eh_padrao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<bool>("UsarHorarioComercial")
                        .HasColumnType("boolean")
                        .HasColumnName("usar_horario_comercial");

                    b.HasKey("Id");

                    b.HasIndex("CalendarioCorporativoId");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("politicas_sla");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.RespostaFormularioChamado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<Guid>("CampoFormularioServicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("campo_formulario_servico_id");

                    b.Property<Guid>("ChamadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("chamado_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<Guid>("FormularioServicoVersaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("formulario_servico_versao_id");

                    b.Property<string>("Valor")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("valor");

                    b.Property<string>("ValoresJson")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("valores_json");

                    b.HasKey("Id");

                    b.HasIndex("CampoFormularioServicoId")
                        .HasDatabaseName("ix_resp_form_campo");

                    b.HasIndex("ChamadoId")
                        .HasDatabaseName("ix_resp_form_chamado");

                    b.HasIndex("ChamadoId", "CampoFormularioServicoId")
                        .IsUnique()
                        .HasDatabaseName("ux_resp_form_chamado_cmp");

                    b.HasIndex("ChamadoId", "FormularioServicoVersaoId")
                        .HasDatabaseName("ix_resp_form_chamado_ver");

                    b.HasIndex("FormularioServicoVersaoId")
                        .HasDatabaseName("ix_resp_form_versao");

                    b.ToTable("respostas_formulario_chamado");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.FormularioServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<Guid>("CatalogoServicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalogo_servico_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("CatalogoServicoId")
                        .IsUnique()
                        .HasDatabaseName("ux_formularios_servico_catalogo_servico_id");

                    b.ToTable("formularios_servico");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.FormularioServicoVersao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<Guid>("FormularioServicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("formulario_servico_id");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<bool>("Publicada")
                        .HasColumnType("boolean")
                        .HasColumnName("publicada");

                    b.Property<DateTime?>("PublicadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publicado_em");

                    b.HasKey("Id");

                    b.HasIndex("FormularioServicoId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ux_form_serv_versao_num");

                    b.ToTable("formularios_servico_versoes");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.OpcaoCampoFormularioServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<Guid>("CampoFormularioServicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("campo_formulario_servico_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<string>("Rotulo")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("rotulo");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("CampoFormularioServicoId", "Ordem")
                        .IsUnique()
                        .HasDatabaseName("ux_opcao_form_serv_ordem");

                    b.HasIndex("CampoFormularioServicoId", "Valor")
                        .IsUnique()
                        .HasDatabaseName("ux_opcao_form_serv_valor");

                    b.ToTable("opcoes_campos_formulario_servico");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.CatalogoServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<Guid?>("ArtigoBaseConhecimentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("artigo_base_conhecimento_id");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<Guid?>("DepartamentoResponsavelId")
                        .HasColumnType("uuid")
                        .HasColumnName("departamento_responsavel_id");

                    b.Property<Guid?>("GrupoTecnicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_tecnico_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<bool>("PermiteAberturaChamado")
                        .HasColumnType("boolean")
                        .HasColumnName("permite_abertura_chamado");

                    b.Property<Guid?>("PrioridadePadraoId")
                        .HasColumnType("uuid")
                        .HasColumnName("prioridade_padrao_id");

                    b.Property<bool>("RequerAprovacao")
                        .HasColumnType("boolean")
                        .HasColumnName("requer_aprovacao");

                    b.Property<Guid?>("SlaPadraoId")
                        .HasColumnType("uuid")
                        .HasColumnName("sla_padrao_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("slug");

                    b.Property<Guid?>("SubcategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("subcategoria_id");

                    b.HasKey("Id");

                    b.HasIndex("ArtigoBaseConhecimentoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("DepartamentoResponsavelId");

                    b.HasIndex("GrupoTecnicoId");

                    b.HasIndex("PrioridadePadraoId");

                    b.HasIndex("SlaPadraoId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("SubcategoriaId");

                    b.ToTable("catalogos_servico");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.TipoAtivoInventario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("tipos_ativos_inventario");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.Departamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sigla");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.HasIndex("Sigla")
                        .IsUnique();

                    b.ToTable("departamentos");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("email");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("login");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.SubcategoriaChamado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<Guid>("CategoriaChamadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_chamado_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaChamadoId");

                    b.HasIndex("Nome");

                    b.ToTable("subcategorias_chamado");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.StatusChamado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<int>("Codigo")
                        .HasColumnType("integer")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("status_chamado");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.Prioridade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer")
                        .HasColumnName("nivel");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Nivel")
                        .IsUnique();

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("prioridades");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.RoadmapChecklistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<bool>("Concluido")
                        .HasColumnType("boolean")
                        .HasColumnName("concluido");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("descricao");

                    b.Property<int>("Grupo")
                        .HasColumnType("integer")
                        .HasColumnName("grupo");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("boolean")
                        .HasColumnName("obrigatorio");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<Guid>("RoadmapItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("roadmap_item_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("ix_roadmap_checklist_itens_ativo");

                    b.HasIndex("Grupo")
                        .HasDatabaseName("ix_roadmap_checklist_itens_grupo");

                    b.HasIndex("RoadmapItemId")
                        .HasDatabaseName("ix_roadmap_checklist_itens_roadmap_item_id");

                    b.HasIndex("RoadmapItemId", "Ordem")
                        .HasDatabaseName("ix_roadmap_checklist_itens_item_ordem");

                    b.ToTable("roadmap_checklist_itens", (string)null);
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.RoadmapItsmItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("area");

                    b.Property<string>("AtencaoTecnica")
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)")
                        .HasColumnName("atencao_tecnica");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("categoria");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<string>("CriterioAceite")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("criterio_aceite");

                    b.Property<DateTime?>("DataConclusaoTecnica")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_conclusao_tecnica");

                    b.Property<DateTime?>("DataHomologacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_homologacao");

                    b.Property<int>("Decisao")
                        .HasColumnType("integer")
                        .HasColumnName("decisao");

                    b.Property<string>("EvidenciaImplementacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("evidencia_implementacao");

                    b.Property<int>("Impacto")
                        .HasColumnType("integer")
                        .HasColumnName("impacto");

                    b.Property<string>("Objetivo")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("objetivo");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)")
                        .HasColumnName("observacao");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<string>("PendenciasHomologacao")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("pendencias_homologacao");

                    b.Property<string>("PendenciasTecnicas")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("pendencias_tecnicas");

                    b.Property<int>("PercentualImplementacao")
                        .HasColumnType("integer")
                        .HasColumnName("percentual_implementacao");

                    b.Property<DateTime?>("PrazoAlvo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("prazo_alvo");

                    b.Property<int>("Prioridade")
                        .HasColumnType("integer")
                        .HasColumnName("prioridade");

                    b.Property<string>("ProximaAcao")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("proxima_acao");

                    b.Property<string>("Responsavel")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("responsavel");

                    b.Property<Guid?>("RoadmapCategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("roadmap_categoria_id");

                    b.Property<string>("SituacaoAtual")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)")
                        .HasColumnName("situacao_atual");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("StatusImplementacao")
                        .HasColumnType("integer")
                        .HasColumnName("status_implementacao");

                    b.Property<int>("StatusTecnico")
                        .HasColumnType("integer")
                        .HasColumnName("status_tecnico");

                    b.HasKey("Id");

                    b.HasIndex("RoadmapCategoriaId")
                        .HasDatabaseName("ix_roadmap_itsm_itens_roadmap_categoria_id");

                    b.HasIndex("Ordem", "Categoria")
                        .HasDatabaseName("ix_roadmap_itsm_itens_ordem_categoria");

                    b.ToTable("roadmap_itsm_itens", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
