// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SGX.SistemaChamado.Infrastructure.Persistence;

#nullable disable

namespace SGX.SistemaChamado.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SGXSistemaChamadoDbContext))]
    [Migration("20260509025714_AddRoadmapItsmModule")]
    partial class AddRoadmapItsmModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.AnexoChamado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("caminho");

                    b.Property<Guid>("ChamadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("chamado_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("nome_arquivo");

                    b.Property<string>("NomeArquivoArmazenado")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("nome_arquivo_armazenado");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanho_bytes");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("anexos_chamado", (string)null);
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.CategoriaChamado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<Guid?>("DepartamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("departamento_id");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("categorias_chamado", (string)null);
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.Chamado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AbertoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aberto_em");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<Guid?>("DepartamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("departamento_id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("descricao");

                    b.Property<DateTime?>("EncerradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("encerrado_em");

                    b.Property<int>("Origem")
                        .HasColumnType("integer")
                        .HasColumnName("origem");

                    b.Property<Guid>("PrioridadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("prioridade_id");

                    b.Property<Guid?>("ResponsavelId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsavel_id");

                    b.Property<Guid>("SolicitanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("solicitante_id");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_chamados_codigo");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("PrioridadeId");

                    b.HasIndex("ResponsavelId");

                    b.HasIndex("SolicitanteId");

                    b.HasIndex("StatusId");

                    b.ToTable("chamados", (string)null);
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.ComentarioChamado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<Guid>("ChamadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("chamado_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<bool>("Interno")
                        .HasColumnType("boolean")
                        .HasColumnName("interno");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("mensagem");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("comentarios_chamado", (string)null);
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.Departamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("nome");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sigla");

                    b.HasKey("Id");

                    b.HasIndex("Sigla")
                        .IsUnique()
                        .HasDatabaseName("ux_departamentos_sigla");

                    b.ToTable("departamentos", (string)null);
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.HistoricoChamado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChamadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("chamado_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("descricao");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("historicos_chamado", (string)null);
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.LogIntegracaoEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Assunto")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("assunto");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<Guid?>("ChamadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("chamado_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<DateTime?>("DataProcessamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_processamento");

                    b.Property<DateTime>("DataRecebimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_recebimento");

                    b.Property<string>("Erro")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("erro");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("fingerprint");

                    b.Property<string>("MessageId")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("message_id");

                    b.Property<string>("NomeRemetente")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("nome_remetente");

                    b.Property<string>("Remetente")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("remetente");

                    b.Property<int>("StatusProcessamento")
                        .HasColumnType("integer")
                        .HasColumnName("status_processamento");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoId")
                        .HasDatabaseName("ix_logs_integracao_email_chamado_id");

                    b.HasIndex("DataRecebimento")
                        .HasDatabaseName("ix_logs_integracao_email_data_recebimento");

                    b.HasIndex("Fingerprint")
                        .IsUnique()
                        .HasDatabaseName("ux_logs_integracao_email_fingerprint");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasDatabaseName("ux_logs_integracao_email_message_id")
                        .HasFilter("\"message_id\" IS NOT NULL");

                    b.HasIndex("StatusProcessamento")
                        .HasDatabaseName("ix_logs_integracao_email_status");

                    b.ToTable("logs_integracao_email", (string)null);
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.ParametroSistema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("chave");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<bool>("Sensivel")
                        .HasColumnType("boolean")
                        .HasColumnName("sensivel");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("Chave")
                        .IsUnique()
                        .HasDatabaseName("ux_parametros_sistema_chave");

                    b.ToTable("parametros_sistema", (string)null);
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.PerfilAcesso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<int>("TipoPerfil")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_perfil");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ux_perfis_acesso_nome");

                    b.ToTable("perfis_acesso", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPor = "seed.sistema",
                            Descricao = "Perfil com acesso total ao SGX Sistema de Chamados.",
                            Nome = "Administrador",
                            TipoPerfil = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPor = "seed.sistema",
                            Descricao = "Perfil responsavel por atendimento e resolucao dos chamados.",
                            Nome = "Atendente",
                            TipoPerfil = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPor = "seed.sistema",
                            Descricao = "Perfil de abertura e acompanhamento de chamados.",
                            Nome = "Solicitante",
                            TipoPerfil = 3
                        });
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.PrioridadeChamado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer")
                        .HasColumnName("nivel");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<int>("PrazoPrimeiraRespostaHoras")
                        .HasColumnType("integer")
                        .HasColumnName("prazo_primeira_resposta_horas");

                    b.Property<int>("PrazoResolucaoHoras")
                        .HasColumnType("integer")
                        .HasColumnName("prazo_resolucao_horas");

                    b.HasKey("Id");

                    b.HasIndex("Nivel")
                        .IsUnique()
                        .HasDatabaseName("ux_prioridades_chamado_nivel");

                    b.ToTable("prioridades_chamado", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555551"),
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPor = "seed.sistema",
                            Descricao = "Impacto baixo.",
                            Nivel = 1,
                            Nome = "Baixa",
                            PrazoPrimeiraRespostaHoras = 8,
                            PrazoResolucaoHoras = 48
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555552"),
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPor = "seed.sistema",
                            Descricao = "Impacto moderado.",
                            Nivel = 2,
                            Nome = "Media",
                            PrazoPrimeiraRespostaHoras = 4,
                            PrazoResolucaoHoras = 24
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555553"),
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPor = "seed.sistema",
                            Descricao = "Impacto alto.",
                            Nivel = 3,
                            Nome = "Alta",
                            PrazoPrimeiraRespostaHoras = 2,
                            PrazoResolucaoHoras = 8
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555554"),
                            Ativo = true,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPor = "seed.sistema",
                            Descricao = "Impacto critico.",
                            Nivel = 4,
                            Nome = "Critica",
                            PrazoPrimeiraRespostaHoras = 1,
                            PrazoResolucaoHoras = 4
                        });
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.RoadmapItsmItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("area");

                    b.Property<string>("AtencaoTecnica")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)")
                        .HasColumnName("atencao_tecnica");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("categoria");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<int>("Decisao")
                        .HasColumnType("integer")
                        .HasColumnName("decisao");

                    b.Property<int>("Impacto")
                        .HasColumnType("integer")
                        .HasColumnName("impacto");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)")
                        .HasColumnName("observacao");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<DateTime?>("PrazoAlvo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("prazo_alvo");

                    b.Property<int>("Prioridade")
                        .HasColumnType("integer")
                        .HasColumnName("prioridade");

                    b.Property<string>("Responsavel")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("responsavel");

                    b.Property<string>("SituacaoAtual")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)")
                        .HasColumnName("situacao_atual");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Ordem", "Categoria")
                        .HasDatabaseName("ix_roadmap_itsm_itens_ordem_categoria");

                    b.ToTable("roadmap_itsm_itens", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777701"),
                            Area = "Abertura de chamado pelo portal",
                            AtencaoTecnica = "Demonstrar fluxo completo: abrir, anexar, acompanhar",
                            Ativo = true,
                            Categoria = "Portal",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPor = "seed.sistema",
                            Decisao = 4,
                            Impacto = 1,
                            Ordem = 1,
                            Prioridade = 1,
                            SituacaoAtual = "Prevista no portal /portal",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777702"),
                            Area = "Abertura por e-mail",
                            AtencaoTecnica = "Testar e mostrar correlacao por codigo, assunto e resposta",
                            Ativo = true,
                            Categoria = "Integracao",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPor = "seed.sistema",
                            Decisao = 4,
                            Impacto = 1,
                            Ordem = 2,
                            Prioridade = 1,
                            SituacaoAtual = "Prevista via Worker IMAP",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777703"),
                            Area = "Perfis de acesso",
                            AtencaoTecnica = "Validar permissoes finas por tela e acao",
                            Ativo = true,
                            Categoria = "Seguranca",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPor = "seed.sistema",
                            Decisao = 4,
                            Impacto = 1,
                            Ordem = 3,
                            Prioridade = 1,
                            SituacaoAtual = "Administrador, Atendente e Solicitante",
                            Status = 3
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777704"),
                            Area = "Autenticacao corporativa",
                            AtencaoTecnica = "Preparar explicacao clara: Azure autentica, SGX autoriza",
                            Ativo = true,
                            Categoria = "Seguranca",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPor = "seed.sistema",
                            Decisao = 4,
                            Impacto = 1,
                            Ordem = 4,
                            Prioridade = 1,
                            SituacaoAtual = "Entra ID/Azure AD previsto",
                            Status = 4
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777705"),
                            Area = "SLA",
                            AtencaoTecnica = "Mostrar regra de prazo, pausa, resposta e encerramento",
                            Ativo = true,
                            Categoria = "Operacao",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPor = "seed.sistema",
                            Decisao = 4,
                            Impacto = 1,
                            Ordem = 5,
                            Prioridade = 1,
                            SituacaoAtual = "Estrutura prevista com controle e configuracao",
                            Status = 3
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777706"),
                            Area = "Historico/auditoria",
                            AtencaoTecnica = "Garantir que mudancas relevantes sejam registradas",
                            Ativo = true,
                            Categoria = "Governanca",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPor = "seed.sistema",
                            Decisao = 4,
                            Impacto = 1,
                            Ordem = 6,
                            Prioridade = 1,
                            SituacaoAtual = "Previsto com historico do chamado",
                            Status = 3
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777707"),
                            Area = "Comentarios e anexos",
                            AtencaoTecnica = "Testar upload, download, visibilidade publica/interna",
                            Ativo = true,
                            Categoria = "Operacao",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPor = "seed.sistema",
                            Decisao = 4,
                            Impacto = 1,
                            Ordem = 7,
                            Prioridade = 1,
                            SituacaoAtual = "Previsto",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777708"),
                            Area = "Cadastros administrativos",
                            AtencaoTecnica = "Verificar se permitem inativacao e parametrizacao",
                            Ativo = true,
                            Categoria = "Administracao",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPor = "seed.sistema",
                            Decisao = 4,
                            Impacto = 2,
                            Ordem = 8,
                            Prioridade = 2,
                            SituacaoAtual = "Categorias, prioridades, status e departamentos",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777709"),
                            Area = "Dashboard",
                            AtencaoTecnica = "Levar indicadores simples: abertos, vencidos, por status e por atendente",
                            Ativo = true,
                            Categoria = "Gestao",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPor = "seed.sistema",
                            Decisao = 4,
                            Impacto = 1,
                            Ordem = 9,
                            Prioridade = 2,
                            SituacaoAtual = "Previsto",
                            Status = 3
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777710"),
                            Area = "Base de conhecimento",
                            AtencaoTecnica = "Pode ser GAP assumido para evolucao",
                            Ativo = true,
                            Categoria = "Conhecimento",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPor = "seed.sistema",
                            Decisao = 2,
                            Impacto = 2,
                            Ordem = 10,
                            Prioridade = 2,
                            SituacaoAtual = "Nao ha evidencia forte",
                            Status = 4
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777711"),
                            Area = "Inventario/ativos",
                            AtencaoTecnica = "Nao prometer equivalencia com GLPI nesse ponto",
                            Ativo = true,
                            Categoria = "Ativos",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPor = "seed.sistema",
                            Decisao = 2,
                            Impacto = 2,
                            Ordem = 11,
                            Prioridade = 3,
                            SituacaoAtual = "Nao ha evidencia forte",
                            Status = 4
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777712"),
                            Area = "Catalogo de servicos",
                            AtencaoTecnica = "Pode precisar virar recurso mais formal",
                            Ativo = true,
                            Categoria = "Catalogo",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPor = "seed.sistema",
                            Decisao = 2,
                            Impacto = 1,
                            Ordem = 12,
                            Prioridade = 2,
                            SituacaoAtual = "Parcial, via categorias/departamentos",
                            Status = 3
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777713"),
                            Area = "Aprovacao de chamados",
                            AtencaoTecnica = "Tratar como melhoria futura se for exigencia",
                            Ativo = true,
                            Categoria = "Workflow",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPor = "seed.sistema",
                            Decisao = 2,
                            Impacto = 2,
                            Ordem = 13,
                            Prioridade = 2,
                            SituacaoAtual = "Nao ha evidencia forte",
                            Status = 4
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777714"),
                            Area = "Notificacoes",
                            AtencaoTecnica = "Validar e/ou planejar e-mail/notificacao por evento",
                            Ativo = true,
                            Categoria = "Comunicacao",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPor = "seed.sistema",
                            Decisao = 4,
                            Impacto = 1,
                            Ordem = 14,
                            Prioridade = 1,
                            SituacaoAtual = "Nao ficou suficientemente evidente",
                            Status = 4
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777715"),
                            Area = "Relatorios avancados",
                            AtencaoTecnica = "Planejar exportacao/filtros gerenciais",
                            Ativo = true,
                            Categoria = "Gestao",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPor = "seed.sistema",
                            Decisao = 2,
                            Impacto = 2,
                            Ordem = 15,
                            Prioridade = 2,
                            SituacaoAtual = "Nao ficou suficientemente evidente",
                            Status = 4
                        });
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.SlaConfiguracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<Guid?>("DepartamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("departamento_id");

                    b.Property<int>("PrazoPrimeiraRespostaHoras")
                        .HasColumnType("integer")
                        .HasColumnName("prazo_primeira_resposta_horas");

                    b.Property<int>("PrazoResolucaoHoras")
                        .HasColumnType("integer")
                        .HasColumnName("prazo_resolucao_horas");

                    b.Property<Guid>("PrioridadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("prioridade_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("PrioridadeId");

                    b.ToTable("sla_configuracoes", (string)null);
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.SlaControle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<Guid>("ChamadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("chamado_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<bool>("EstaPausado")
                        .HasColumnType("boolean")
                        .HasColumnName("esta_pausado");

                    b.Property<bool>("EstaVencido")
                        .HasColumnType("boolean")
                        .HasColumnName("esta_vencido");

                    b.Property<DateTime?>("PausadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pausado_em");

                    b.Property<DateTime>("PrazoPrimeiraRespostaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("prazo_primeira_resposta_em");

                    b.Property<DateTime>("PrazoResolucaoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("prazo_resolucao_em");

                    b.Property<DateTime?>("PrimeiraRespostaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("primeira_resposta_em");

                    b.Property<DateTime?>("ResolvidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolvido_em");

                    b.Property<int>("TotalMinutosPausado")
                        .HasColumnType("integer")
                        .HasColumnName("total_minutos_pausado");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoId")
                        .IsUnique()
                        .HasDatabaseName("ux_sla_controles_chamado_id");

                    b.ToTable("sla_controles", (string)null);
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.StatusChamado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<int>("Codigo")
                        .HasColumnType("integer")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<bool>("EhStatusFinal")
                        .HasColumnType("boolean")
                        .HasColumnName("eh_status_final");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<bool>("PausaSla")
                        .HasColumnType("boolean")
                        .HasColumnName("pausa_sla");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_status_chamado_codigo");

                    b.ToTable("status_chamado", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444441"),
                            Ativo = true,
                            Codigo = 1,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPor = "seed.sistema",
                            Descricao = "Chamado aberto e aguardando atendimento.",
                            EhStatusFinal = false,
                            Nome = "Aberto",
                            PausaSla = false
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444442"),
                            Ativo = true,
                            Codigo = 2,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPor = "seed.sistema",
                            Descricao = "Chamado em atendimento pela equipe.",
                            EhStatusFinal = false,
                            Nome = "Em Atendimento",
                            PausaSla = false
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444443"),
                            Ativo = true,
                            Codigo = 3,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPor = "seed.sistema",
                            Descricao = "Chamado aguardando retorno do solicitante.",
                            EhStatusFinal = false,
                            Nome = "Aguardando Solicitante",
                            PausaSla = true
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Ativo = true,
                            Codigo = 4,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPor = "seed.sistema",
                            Descricao = "Chamado resolvido e aguardando encerramento.",
                            EhStatusFinal = false,
                            Nome = "Resolvido",
                            PausaSla = false
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444445"),
                            Ativo = true,
                            Codigo = 5,
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoPor = "seed.sistema",
                            Descricao = "Chamado encerrado.",
                            EhStatusFinal = true,
                            Nome = "Encerrado",
                            PausaSla = false
                        });
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("atualizado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<Guid?>("DepartamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("departamento_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("login");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("nome");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer")
                        .HasColumnName("situacao");

                    b.Property<DateTime?>("UltimoAcessoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acesso_em");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_usuarios_email");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("ux_usuarios_login");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.UsuarioPerfilAcesso", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("PerfilAcessoId")
                        .HasColumnType("uuid")
                        .HasColumnName("perfil_acesso_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("criado_por");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("UsuarioId", "PerfilAcessoId");

                    b.HasIndex("PerfilAcessoId");

                    b.ToTable("usuarios_perfis_acesso", (string)null);
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.AnexoChamado", b =>
                {
                    b.HasOne("SGX.SistemaChamado.Domain.Entities.Chamado", "Chamado")
                        .WithMany("Anexos")
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SGX.SistemaChamado.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chamado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.CategoriaChamado", b =>
                {
                    b.HasOne("SGX.SistemaChamado.Domain.Entities.Departamento", "Departamento")
                        .WithMany("Categorias")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.Chamado", b =>
                {
                    b.HasOne("SGX.SistemaChamado.Domain.Entities.CategoriaChamado", "Categoria")
                        .WithMany("Chamados")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGX.SistemaChamado.Domain.Entities.Departamento", "Departamento")
                        .WithMany("Chamados")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SGX.SistemaChamado.Domain.Entities.PrioridadeChamado", "Prioridade")
                        .WithMany("Chamados")
                        .HasForeignKey("PrioridadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGX.SistemaChamado.Domain.Entities.Usuario", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SGX.SistemaChamado.Domain.Entities.Usuario", "Solicitante")
                        .WithMany()
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGX.SistemaChamado.Domain.Entities.StatusChamado", "Status")
                        .WithMany("Chamados")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Departamento");

                    b.Navigation("Prioridade");

                    b.Navigation("Responsavel");

                    b.Navigation("Solicitante");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.ComentarioChamado", b =>
                {
                    b.HasOne("SGX.SistemaChamado.Domain.Entities.Chamado", "Chamado")
                        .WithMany("Comentarios")
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SGX.SistemaChamado.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chamado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.HistoricoChamado", b =>
                {
                    b.HasOne("SGX.SistemaChamado.Domain.Entities.Chamado", "Chamado")
                        .WithMany("Historicos")
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SGX.SistemaChamado.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Chamado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.LogIntegracaoEmail", b =>
                {
                    b.HasOne("SGX.SistemaChamado.Domain.Entities.Chamado", "Chamado")
                        .WithMany()
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Chamado");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.SlaConfiguracao", b =>
                {
                    b.HasOne("SGX.SistemaChamado.Domain.Entities.CategoriaChamado", "Categoria")
                        .WithMany("SlaConfiguracoes")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SGX.SistemaChamado.Domain.Entities.Departamento", "Departamento")
                        .WithMany("SlaConfiguracoes")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SGX.SistemaChamado.Domain.Entities.PrioridadeChamado", "Prioridade")
                        .WithMany("SlaConfiguracoes")
                        .HasForeignKey("PrioridadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Departamento");

                    b.Navigation("Prioridade");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.SlaControle", b =>
                {
                    b.HasOne("SGX.SistemaChamado.Domain.Entities.Chamado", "Chamado")
                        .WithOne("SlaControle")
                        .HasForeignKey("SGX.SistemaChamado.Domain.Entities.SlaControle", "ChamadoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Chamado");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("SGX.SistemaChamado.Domain.Entities.Departamento", "Departamento")
                        .WithMany("Usuarios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.UsuarioPerfilAcesso", b =>
                {
                    b.HasOne("SGX.SistemaChamado.Domain.Entities.PerfilAcesso", "PerfilAcesso")
                        .WithMany("UsuarioPerfis")
                        .HasForeignKey("PerfilAcessoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGX.SistemaChamado.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioPerfis")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PerfilAcesso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.CategoriaChamado", b =>
                {
                    b.Navigation("Chamados");

                    b.Navigation("SlaConfiguracoes");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.Chamado", b =>
                {
                    b.Navigation("Anexos");

                    b.Navigation("Comentarios");

                    b.Navigation("Historicos");

                    b.Navigation("SlaControle");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.Departamento", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Chamados");

                    b.Navigation("SlaConfiguracoes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.PerfilAcesso", b =>
                {
                    b.Navigation("UsuarioPerfis");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.PrioridadeChamado", b =>
                {
                    b.Navigation("Chamados");

                    b.Navigation("SlaConfiguracoes");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.StatusChamado", b =>
                {
                    b.Navigation("Chamados");
                });

            modelBuilder.Entity("SGX.SistemaChamado.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("UsuarioPerfis");
                });
#pragma warning restore 612, 618
        }
    }
}
