// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SGX.SistemaChamado.Infrastructure.Persistence;

#nullable disable

namespace SGX.SistemaChamado.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SGXSistemaChamadoDbContext))]
    [Migration("20260607235900_ConcluirRegraRejeitarChamadoSprint4Roadmap")]
    partial class ConcluirRegraRejeitarChamadoSprint4Roadmap
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
