app:
  ambiente: producao
  worker:
    email:
      modo-local-habilitado: false

management:
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: WARN
    br.geti.sistemachamado: INFO

