namespace SGX.SistemaChamado.Domain.Enums;

public enum TipoHistoricoChamado
{
    Criado = 1,
    StatusAlterado = 2,
    PrioridadeAlterada = 3,
    CategoriaAlterada = 4,
    ResponsavelAlterado = 5,
    ComentarioAdicionado = 6,
    AnexoAdicionado = 7,
    Encerrado = 8,
    Reaberto = 9,
    IntegracaoEmail = 10,
    ArtigoConhecimentoVinculado = 11,
    ArtigoConhecimentoDesvinculado = 12,
    ChamadoCriadoPorCatalogoServico = 13,
    AtivoVinculado = 14,
    AtivoRemovido = 15,
    AprovacaoSolicitada = 16,
    ChamadoAprovado = 17,
    ChamadoReprovado = 18,
    AprovacaoCancelada = 19,
    RelacionamentoCriado = 20,
    RelacionamentoRecebido = 21,
    RelacionamentoRemovido = 22,
    RelacionamentoRemovidoRecebido = 23,
    ChamadoDerivadoCriado = 24,
    CriadoAPartirDeChamado = 25,
    TarefaCriada = 26,
    TarefaStatusAlterado = 27,
    TarefaCancelada = 28,
    TarefaConcluida = 29,
    AprovacaoCriada = 30,
    AprovacaoAprovada = 31,
    AprovacaoReprovada = 32
}
