export const permissoes = {
  dashboardVisualizar: 'Dashboard.Visualizar',
  chamadosVisualizar: 'Chamados.Visualizar',
  chamadosVisualizarTodos: 'Chamados.VisualizarTodos',
  chamadosAssumir: 'Chamados.Assumir',
  chamadosAtribuir: 'Chamados.Atribuir',
  chamadosEncerrar: 'Chamados.Encerrar',
  usuariosVisualizar: 'Usuarios.Visualizar',
  usuariosGerenciar: 'Usuarios.Gerenciar',
  usuariosRedefinirSenha: 'Usuarios.RedefinirSenha',
  usuariosAlterarPerfis: 'Usuarios.AlterarPerfis',
  perfisVisualizar: 'Perfis.Visualizar',
  perfisGerenciar: 'Perfis.Gerenciar',
  perfisAlterarPermissoes: 'Perfis.AlterarPermissoes',
  parametrosVisualizar: 'Parametros.Visualizar',
  parametrosGerenciar: 'Parametros.Gerenciar',
  integracoesEmailVisualizar: 'IntegracoesEmail.Visualizar',
  integracoesMicrosoftVisualizar: 'IntegracoesMicrosoft.Visualizar',
  integracoesMicrosoftGerenciar: 'IntegracoesMicrosoft.Gerenciar',
  integracoesActiveDirectoryVisualizar: 'IntegracoesActiveDirectory.Visualizar',
  integracoesActiveDirectoryGerenciar: 'IntegracoesActiveDirectory.Gerenciar',
  autenticacaoProvedoresVisualizar: 'AutenticacaoProvedores.Visualizar',
  autenticacaoProvedoresGerenciar: 'AutenticacaoProvedores.Gerenciar',
  notificacoesVisualizar: 'Notificacoes.Visualizar',
  notificacoesGerenciar: 'Notificacoes.Gerenciar',
  cadastrosVisualizar: 'Cadastros.Visualizar',
  roadmapVisualizar: 'Roadmap.Visualizar',
  roadmapGerenciar: 'Roadmap.Gerenciar',
  roadmapImplementacoesVisualizar: 'RoadmapImplementacoes.Visualizar',
  roadmapImplementacoesGerenciar: 'RoadmapImplementacoes.Gerenciar',
  slaVisualizar: 'Sla.Visualizar',
  slaCriar: 'Sla.Criar',
  slaEditar: 'Sla.Editar',
  slaExcluir: 'Sla.Excluir',
  slaAtivarDesativar: 'Sla.AtivarDesativar',
  auditoriaVisualizar: 'Auditoria.Visualizar',
  auditoriaAutenticacaoVisualizar: 'AuditoriaAutenticacao.Visualizar',
  auditoriaGerenciar: 'Auditoria.Gerenciar',
  baseConhecimentoVisualizar: 'BaseConhecimento.Visualizar',
  baseConhecimentoGerenciar: 'BaseConhecimento.Gerenciar',
  baseConhecimentoPublicar: 'BaseConhecimento.Publicar',
  baseConhecimentoArquivar: 'BaseConhecimento.Arquivar',
  baseConhecimentoVincularChamado: 'BaseConhecimento.VincularChamado',
  catalogoServicosVisualizar: 'CatalogoServicos.Visualizar',
  catalogoServicosGerenciar: 'CatalogoServicos.Gerenciar',
  catalogoServicosPublicar: 'CatalogoServicos.Publicar',
  catalogoServicosArquivar: 'CatalogoServicos.Arquivar',
  inventarioAtivosVisualizar: 'InventarioAtivos.Visualizar',
  inventarioAtivosGerenciar: 'InventarioAtivos.Gerenciar',
  inventarioAtivosInativar: 'InventarioAtivos.Inativar',
  inventarioAtivosMovimentar: 'InventarioAtivos.Movimentar',
  inventarioAtivosVincularChamado: 'InventarioAtivos.VincularChamado',
  aprovacaoChamadosVisualizar: 'AprovacaoChamados.Visualizar',
  aprovacaoChamadosGerenciar: 'AprovacaoChamados.Gerenciar',
  aprovacaoChamadosAprovar: 'AprovacaoChamados.Aprovar',
  aprovacaoChamadosReprovar: 'AprovacaoChamados.Reprovar',
  aprovacaoChamadosCancelar: 'AprovacaoChamados.Cancelar',
  relatoriosAvancadosVisualizar: 'RelatoriosAvancados.Visualizar',
  relatoriosAvancadosExportar: 'RelatoriosAvancados.Exportar',
  relatoriosAvancadosGerencial: 'RelatoriosAvancados.Gerencial',
  relatoriosAvancadosOperacional: 'RelatoriosAvancados.Operacional',
  relatoriosAvancadosAuditoria: 'RelatoriosAvancados.Auditoria',
  
  problemasVisualizar: 'Problemas.Visualizar',
  problemasGerenciar: 'Problemas.Gerenciar',
  
  mudancasVisualizar: 'Mudancas.Visualizar',
  mudancasGerenciar: 'Mudancas.Gerenciar',
  
  tarefasVisualizar: 'Tarefas.Visualizar',
  tarefasGerenciar: 'Tarefas.Gerenciar',
} as const


export const permissoesCriticas = [
  permissoes.usuariosGerenciar,
  permissoes.perfisGerenciar,
  permissoes.perfisAlterarPermissoes,
] as const
