app:
  ambiente: producao

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${APP_SECURITY_OAUTH2_ISSUER_URI}

management:
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: WARN
    br.geti.sistemachamado: INFO

